//Gfx converted using Mollusk's PAGfx Converter

//This file contains all the .c, for easier inclusion in a project

#ifdef __cplusplus
extern "C" {
#endif


// Sprite files : 
#include "up_titulo0100.c"
#include "up_titulo1000.c"
#include "up_titzh0100.c"
#include "up_titzh1000.c"
#include "up_titulo0001.c"
#include "up_headerlisten.c"
#include "up_headerhanzi.c"
#include "up_headerhanziattack.c"
#include "up_headernihao.c"
#include "up_headergramm.c"
#include "up_bannernihao10.c"
#include "up_bannernihao01.c"
#include "up_bannerlisten10.c"
#include "up_bannerlisten01.c"
#include "up_bannerhanziattack10.c"
#include "up_bannerhanziattack01.c"
#include "up_bannerhanzi10.c"
#include "up_bannerhanzi01.c"
#include "up_bannergramm10.c"
#include "up_bannergramm01.c"
#include "up_text10.c"
#include "up_text01.c"
#include "up_textscroll01.c"
#include "up_textscroll10.c"
#include "up_hidetext10.c"
#include "up_hidetext01.c"
#include "smiley_aiya.c"
#include "smiley_bigeye.c"
#include "smiley_bigeyes.c"
#include "smiley_dead.c"
#include "smiley_happy.c"
#include "smiley_looking.c"
#include "smiley_normal.c"
#include "smiley_sleepy.c"
#include "smiley_talking.c"
#include "smiley_thinking.c"
#include "smiley_unhappy.c"
#include "smiley_wink.c"
#include "smiley_.c"
#include "smiley_what.c"
#include "btn32grey100.c"
#include "btn32grey010.c"
#include "btn32grey001.c"
#include "btn32blue100.c"
#include "btn32blue010.c"
#include "btn32blue001.c"
#include "btn32green100.c"
#include "btn32green010.c"
#include "btn32green001.c"
#include "btn32yellow100.c"
#include "btn32yellow010.c"
#include "btn32yellow001.c"
#include "btn32red100.c"
#include "btn32red010.c"
#include "btn32red001.c"
#include "btn32violet100.c"
#include "btn32violet010.c"
#include "btn32violet001.c"
#include "btn32orange100.c"
#include "btn32orange010.c"
#include "btn32orange001.c"
#include "txt_ideograma_sp.c"
#include "txt_idioma_en.c"
#include "txt_idioma_sp.c"
#include "btn64grey100.c"
#include "btn64grey010.c"
#include "btn64grey001.c"
#include "btn64green100.c"
#include "btn64green010.c"
#include "btn64green001.c"
#include "btn64red100.c"
#include "btn64red010.c"
#include "btn64red001.c"
#include "hanzi_template.c"
#include "btn32field100.c"
#include "btn32field010.c"
#include "btn32field001.c"
#include "btn32fieldsel100.c"
#include "btn32fieldsel010.c"
#include "btn32fieldsel001.c"
#include "arrow_r.c"
#include "arrow_b.c"
#include "arrow_l.c"
#include "config.c"
#include "logo_rrc2.c"
#include "logo_seal.c"
#include "arrow_hanzi.c"
#include "arrow_play.c"
#include "btn64nope.c"
#include "btn64yeah.c"

// Background files : 
#include "logo_rrc.c"
#include "logo_palib.c"
#include "font_arial.c"
#include "font_system.c"

// Palette files : 
#include "titulo.pal.c"
#include "header.pal.c"
#include "banner.pal.c"
#include "up_text.pal.c"
#include "smiley.pal.c"
#include "btn.pal.c"
#include "btntxt.pal.c"
#include "hanzi.pal.c"
#include "btnima.pal.c"
#include "seal.pal.c"
#include "logo_rrc.pal.c"
#include "logo_palib.pal.c"
#include "font_arial.pal.c"
#include "font_system.pal.c"


#ifdef __cplusplus
}
#endif

