del *.tgf
png2tgf.exe textbox.png
png2tgf.exe dummy32.png
png2tgf.exe btns_add.png
png2tgf.exe btns_bs.png
png2tgf.exe btns_clear.png
png2tgf.exe btns_div.png
png2tgf.exe btns_dot.png
png2tgf.exe btns_end.png
png2tgf.exe btns_help.png
png2tgf.exe btns_mul.png
png2tgf.exe btns_num0.png
png2tgf.exe btns_num1.png
png2tgf.exe btns_num2.png
png2tgf.exe btns_num3.png
png2tgf.exe btns_num4.png
png2tgf.exe btns_num5.png
png2tgf.exe btns_num6.png
png2tgf.exe btns_num7.png
png2tgf.exe btns_num8.png
png2tgf.exe btns_num9.png
png2tgf.exe btns_start.png
png2tgf.exe btns_sub.png
png2tgf.exe cube00.png
png2tgf.exe cube01.png
png2tgf.exe cube02.png
png2tgf.exe cube03.png
png2tgf.exe cube04.png
png2tgf.exe cube05.png
png2tgf.exe cube06.png
png2tgf.exe cube07.png
png2tgf.exe cube08.png
png2tgf.exe cube09.png
png2tgf.exe cube10.png
png2tgf.exe cube11.png
png2tgf.exe cube12.png
png2tgf.exe cube13.png
png2tgf.exe cube14.png
png2tgf.exe cube15.png
png2tgf.exe cube16.png
png2tgf.exe cube17.png
png2tgf.exe cube18.png
png2tgf.exe cube19.png
png2tgf.exe cube20.png
png2tgf.exe cube21.png
png2tgf.exe cube22.png
png2tgf.exe cube23.png
png2tgf.exe cube24.png
png2tgf.exe cube25.png
png2tgf.exe cube26.png
png2tgf.exe cube27.png
png2tgf.exe cube28.png
png2tgf.exe cube29.png
png2tgf.exe cube30.png
png2tgf.exe cube31.png
ren *.bin *.
move *.b15 ..\b15
move *.tgf ..\tgf
pause
