#pragma once

enum ESkinFiles {
  ESF_btns_add_tgf,
  ESF_btns_bs_tgf,
  ESF_btns_clear_tgf,
  ESF_btns_div_tgf,
  ESF_btns_dot_tgf,
  ESF_btns_end_tgf,
  ESF_btns_help_tgf,
  ESF_btns_mul_tgf,
  ESF_btns_num0_tgf,
  ESF_btns_num1_tgf,
  ESF_btns_num2_tgf,
  ESF_btns_num3_tgf,
  ESF_btns_num4_tgf,
  ESF_btns_num5_tgf,
  ESF_btns_num6_tgf,
  ESF_btns_num7_tgf,
  ESF_btns_num8_tgf,
  ESF_btns_num9_tgf,
  ESF_btns_start_tgf,
  ESF_btns_sub_tgf,
  ESF_cube00_tgf,
  ESF_cube01_tgf,
  ESF_cube02_tgf,
  ESF_cube03_tgf,
  ESF_cube04_tgf,
  ESF_cube05_tgf,
  ESF_cube06_tgf,
  ESF_cube07_tgf,
  ESF_cube08_tgf,
  ESF_cube09_tgf,
  ESF_cube10_tgf,
  ESF_cube11_tgf,
  ESF_cube12_tgf,
  ESF_cube13_tgf,
  ESF_cube14_tgf,
  ESF_cube15_tgf,
  ESF_cube16_tgf,
  ESF_cube17_tgf,
  ESF_cube18_tgf,
  ESF_cube19_tgf,
  ESF_cube20_tgf,
  ESF_cube21_tgf,
  ESF_cube22_tgf,
  ESF_cube23_tgf,
  ESF_cube24_tgf,
  ESF_cube25_tgf,
  ESF_cube26_tgf,
  ESF_cube27_tgf,
  ESF_cube28_tgf,
  ESF_cube29_tgf,
  ESF_cube30_tgf,
  ESF_cube31_tgf,
  ESF_dummy32_tgf,
  ESF_helpj0_b15,
  ESF_helpj1_b15,
  ESF_helpj2_b15,
  ESF_helpj3_b15,
  ESF_license_b15,
  ESF_mainbg_b15,
  ESF_mathfont_b15,
  ESF_settings_b15,
  ESF_textbox_tgf,
  ESF_Count,
};

extern void SkinPack_Init(void);
extern void SkinPack_Free(void);

extern CglB15* SkinPack_LoadB15(ESkinFiles ESF);
extern CglTGF* SkinPack_LoadTGF(ESkinFiles ESF);
